// ReactVersion/tienda/components/loginComponent.jsx
import React from 'react';
import { login } from '../assistant/assistant'

const divbgrHtml  = {
  display: 'table',
  margin: 'auto',
  height: '100vh',
  backgroundImage: 'linear-gradient(to bottom, rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0.8)), url(\'/assets/img/login-fondo.jpg\')'
}

const divBody  = {
  width: '100vw',
  display: 'table-cell',
  verticalAlign: 'middle',
  color: 'white'
}

const error = {
    color: 'red'
}

class LoginComponent extends React.Component{
    constructor(){
      super();
      this.state = {value: '', passwordVal:'', error:''};
      this.handleChange = this.handleChange.bind(this);
      this.handleChangePassword = this.handleChangePassword.bind(this);
      this.handleSubmit = this.handleSubmit.bind(this);
    }

    handleChange(event) {
      this.setState({value: event.target.value});
    }

    handleChangePassword(event) {
      this.setState({passwordVal: event.target.value});
    }

    handleSubmit(event) {
      event.preventDefault();
      login(this.state.value, this.state.passwordVal)
        .then(()=>{
          this.props.history.push('/home')
        })
        .catch((error) => {
            this.setState({error: 'email'});
          })
    }

    render(){
      return (<div style={divbgrHtml}>
        <div style={divBody}>
          <div className="col-sm-6 col-sm-offset-3">
            <h4 className="text-center">Inicia Sesion</h4>
            <form onSubmit={this.handleSubmit}>
              <div className="form-group">
                <label htmlFor="email-input">Correo electrónico</label>
                <input type="email" className="form-control" id="email-input" name="email" required value={this.state.value} onChange={this.handleChange} />
              </div>
              <div className="form-group">
                <label htmlFor="password-input">Contraseña</label>
                <input type="password" className="form-control" id="password-input" name="password" required value={this.state.passwordVal} onChange={this.handleChangePassword}/>
              </div>
              <label style={error}>{(() => {
                      switch (this.state.error) {
                        case "email":   return "Usuario/Contraseña no validos";
                        default:      return "";
                      }
                    })()}</label>
              <button type="submit" className="btn btn-info  center-block"> Ingresar </button>
            </form>
          </div>
        </div>
      </div>);
    }
}

export default LoginComponent;

// AngularVersion/tienda-online/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { AngularFireAuth } from 'angularfire2/auth';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  errorLogin:boolean = false;
  constructor(public afAuth: AngularFireAuth, private router: Router) { }

  ngOnInit() {
  }

  login(email, password) {
      this.afAuth.auth.signInWithEmailAndPassword(email, password).then(()=>{
        this.router.navigateByUrl('/home');
      })
      .catch((error) => {
        this.errorLogin = true;
      })
  }

}

<div class="div-html image-login">
  <div class="div-body">
    <div class="col-sm-6 col-sm-offset-3">
      <h4 class="text-center">Inicia Sesion</h4>
      <form>
        <div class="form-group">
          <label for="email-input">Correo electrónico</label>
          <input type="email" class="form-control" id="email-input" #email name="email" required pattern="[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?">
        </div>
        <div class="form-group">
          <label for="password-input">Contraseña</label>
          <input type="password" class="form-control" id="password-input" #password name="password" required>
        </div>
        <label class="error" *ngIf="errorLogin">Usuario/Contraseña no validos</label>
        <button class="btn btn-success center-block" type="button" (click)="login(email.value, password.value)">Ingresar</button>
      </form>
    </div>
  </div>
</div>
